### ISSUE TITLE
Failed to load a language-rust-treesitter package grammar

### ISSUE THREAD

**Issue by luolong** [GrayJack/language-rust-treesitter#2]
[Enter steps to reproduce:]

1.    Atom is failing to load language-rust-treesitter pacage, below is the error

**Atom**: 1.52.0 x64
**Electron**: 6.1.12
**OS**: Mac OS X 10.15.7
**Thrown From**: [language-rust-treesitter](https://github.com/GrayJack/language-rust-treesitter) package 1.4.0

### Stack Trace

Failed to load a language-rust-treesitter package grammar

```
At The module '/Users/rolandtepp/.atom/packages/language-rust-treesitter/node_modules/tree-sitter-rust/build/Release/tree_sitter_rust_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 70. This version of Node.js requires
NODE_MODULE_VERSION 73. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`). in /Users/rolandtepp/.atom/packages/language-rust-treesitter/grammars/tree-sitter-rust.cson

Error: The module '/Users/rolandtepp/.atom/packages/language-rust-treesitter/node_modules/tree-sitter-rust/build/Release/tree_sitter_rust_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 70. This version of Node.js requires
NODE_MODULE_VERSION 73. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func (electron/js2c/asar.js:138:31)
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:828:18)
    at Object.func (electron/js2c/asar.js:138:31)
    at Object.func [as .node] (electron/js2c/asar.js:138:31)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146814)
    at /packages/language-rust-treesitter/node_modules/tree-sitter-rust/index.js:2:20)
    at /packages/language-rust-treesitter/node_modules/tree-sitter-rust/index.js:15:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:16:16)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:695478)
    at new TreeSitterGrammar (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3109595)
    at GrammarRegistry.createGrammar (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:360618)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:360459
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:582485
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
  at /packages/language-rust-treesitter/grammars/tree-sitter-rust.cson:1:1
```

### Commands

```
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
atom-java-decompiler 0.1.2 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
editorconfig 2.6.1 
Hydrogen 2.14.6 
ide-java 0.9.1 
ide-kotlin 0.5.0 
ide-rust 0.22.0-beta.3 
language-gradle 0.1.0 
language-groovy 0.7.0 
language-nginx 0.8.0 
language-powershell 5.0.0 
language-rust-treesitter 1.4.0 
linter-tree-sitter 0.1.3 
minimap-tree-sitter-syntax 0.0.0 
terminus 4.0.6 
tree-sitter-syntax-visualizer 0.0.2 
wakatime 9.0.2 
```

**Comment by luolong** [comment]
It appears recompiling the packages within Atom fixed the issue.

Simple steps to fix the issue:

1. Click on a red bug icon in the Atom footer. This will show list of plug/ins that need to be rebuilt
2. Click on "Rebuild all" button and wait until it's done
3. After all plug-ins have been successfully rebuilt, click on the "Reload Atom" button
4. Enjoy
